image:
  repository: ghcr.io/japan7/nanalook
  tag: main@sha256:4b0d22acb8e7117e17310b5249b2a13cca423a4aae1ea38bb7c30af48de45740
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  clientUsername: ""
  clientPassword: ""
  customClientId: ""
  customClientUsername: ""

ingress:
  host: ""
  annotations: {}
