image:
  repository: ghcr.io/japan7/nanalook
  tag: main@sha256:69459f613e9879387ec027370065e11a08ff3ed8392a8f1df36b7a2f0d66f63d
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  clientUsername: ""
  clientPassword: ""
  customClientId: ""
  customClientUsername: ""

ingress:
  host: ""
  annotations: {}
