image:
  repository: ghcr.io/japan7/nanalook
  tag: main@sha256:e54037655f3036ed51044cb9aa8116bfa0060604b0738bb277b5f557f8918cf5
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  clientUsername: ""
  clientPassword: ""
  customClientId: ""
  customClientUsername: ""

ingress:
  host: ""
  annotations: {}
