image:
  repository: ghcr.io/japan7/nanalook
  tag: main@sha256:a55e6c4de413bb411942e55454929a815279fe8709b4ea2a98c1f0cd2901ee66
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  clientUsername: ""
  clientPassword: ""
  customClientId: ""
  customClientUsername: ""

ingress:
  host: ""
  annotations: {}
