image:
  repository: ghcr.io/japan7/nanalook
  tag: main@sha256:4357d43609a2c3c5a601bda22dc8a90ad06095fed0bc6cfc33704517e3ad9524
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  clientUsername: ""
  clientPassword: ""
  customClientId: ""
  customClientUsername: ""

ingress:
  host: ""
  annotations: {}
