image:
  repository: ghcr.io/japan7/nanalook
  tag: main@sha256:41f05f1e8eb021d2a7d2462bae628ce4ce9479101988d8eebdbebe16d15792bf
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  clientUsername: ""
  clientPassword: ""
  customClientId: ""
  customClientUsername: ""

ingress:
  host: ""
  annotations: {}
