image:
  repository: ghcr.io/japan7/nanalook
  tag: main@sha256:86e1139bcddfd16111de2d1c20cb2cf918828d9926c762a2ba780d466750daa1
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  clientUsername: ""
  clientPassword: ""
  customClientId: ""
  customClientUsername: ""

ingress:
  host: ""
  annotations: {}
