image:
  repository: ghcr.io/japan7/nanalook
  tag: main@sha256:93ef0842ba935bde744ac17b03021e5e07e3631377ff8853859086356af10053
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  clientUsername: ""
  clientPassword: ""
  customClientId: ""
  customClientUsername: ""

ingress:
  host: ""
  annotations: {}
