image:
  repository: ghcr.io/japan7/dakara-server
  tag: master@sha256:142c4145204c249e9b3375b258d34fd8f1b0aca466fc4765fdbd07f09af95e2a
  pullPolicy: ""

replicaCount: 1

affinity: {}

secretKey: ""

smtp:
  enabled: true
  sender: ""
  host: ""
  port: 465
  ssl: "True"
  user: ""
  password: ""

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
  labels: {}

ingress:
  host: ""
  annotations: {}
