image:
  repository: ghcr.io/japan7/dakara-server
  tag: master@sha256:3caaff5932a1f17e0e7f9ae5d2d6133239c7057e7e643fd17044ef189db3d538
  pullPolicy: ""

replicaCount: 1

affinity: {}

secretKey: ""

smtp:
  enabled: true
  sender: ""
  host: ""
  port: 465
  ssl: "True"
  user: ""
  password: ""

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
  labels: {}

ingress:
  host: ""
  annotations: {}
