image:
  repository: ghcr.io/japan7/dakara-server
  tag: master@sha256:d99cd23675053ab114fcdccbc94c5702dfc815cc64beffcc13f332f8f0e88329
  pullPolicy: ""

replicaCount: 1

affinity: {}

secretKey: ""

smtp:
  enabled: true
  sender: ""
  host: ""
  port: 465
  ssl: "True"
  user: ""
  password: ""

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
  labels: {}

ingress:
  host: ""
  annotations: {}
