image:
  repository: ghcr.io/japan7/dakara-server
  tag: master@sha256:23cb7ec1cadfdeef1ed878b69992b38e391d102916aa789c07de3ba9462c2c2c
  pullPolicy: ""

replicaCount: 1

affinity: {}

secretKey: ""

smtp:
  enabled: true
  sender: ""
  host: ""
  port: 465
  ssl: "True"
  user: ""
  password: ""

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
  labels: {}

ingress:
  host: ""
  annotations: {}
