image:
  repository: ghcr.io/japan7/dakara-server
  tag: master@sha256:208371564ca70494794535347f4fa2f06c4837be39d057731b4c58f87d28c5ad
  pullPolicy: ""

replicaCount: 1

affinity: {}

secretKey: ""

smtp:
  enabled: true
  sender: ""
  host: ""
  port: 465
  ssl: "True"
  user: ""
  password: ""

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
  labels: {}

ingress:
  host: ""
  annotations: {}
