image:
  repository: ghcr.io/japan7/dakara-server
  tag: master@sha256:ab9c52f83a5f786b66364f068cb5675c0cbdfa732fb87ea045b4ba8a7798e98b
  pullPolicy: ""

replicaCount: 1

affinity: {}

secretKey: ""

smtp:
  enabled: true
  sender: ""
  host: ""
  port: 465
  ssl: "True"
  user: ""
  password: ""

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
  labels: {}

ingress:
  host: ""
  annotations: {}
