image:
  repository: ghcr.io/japan7/dakara-server
  tag: master@sha256:2a69bf68f6b0748fc43c4e4a73786b379d746a546000ffc17e1a4867caf3a711
  pullPolicy: ""

replicaCount: 1

affinity: {}

secretKey: ""

smtp:
  enabled: true
  sender: ""
  host: ""
  port: 465
  ssl: "True"
  user: ""
  password: ""

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
  labels: {}

ingress:
  host: ""
  annotations: {}
