image:
  repository: ghcr.io/japan7/dakara-client-web
  tag: master@sha256:7cb7122a88ddb72ed1a007a18c0baa5cab4a7d4b54b74ae24f8adbcc2c2d8102
  pullPolicy: ""

replicaCount: 1

affinity: {}

ingress:
  host: ""
  annotations: {}
