image:
  repository: ghcr.io/japan7/dakara-client-web
  tag: master@sha256:f273a7dba117a4bd3422cb26449205ff6ebda28f5c8cb6ec21d3ad729ec930a3
  pullPolicy: ""

replicaCount: 1

affinity: {}

ingress:
  host: ""
  annotations: {}
