image:
  repository: ghcr.io/japan7/dakara-client-web
  tag: master@sha256:c1d278900e88f384a18d88a4820ccb21ac00a76576954791997667f0fe7a768c
  pullPolicy: ""

replicaCount: 1

affinity: {}

ingress:
  host: ""
  annotations: {}
