image:
  repository: ghcr.io/japan7/dakara-client-web
  tag: master@sha256:3d49b1993660550c7eb7f3d002b6b9042aa215c95e2c13039b0a553f4d1bbadb
  pullPolicy: ""

replicaCount: 1

affinity: {}

ingress:
  host: ""
  annotations: {}
