image:
  repository: ghcr.io/japan7/dakara-client-web
  tag: master@sha256:0b27b718faa2a86428a0a91b07aeab0d591a4b0a9e726c5baeaa4ef651721364
  pullPolicy: ""

replicaCount: 1

affinity: {}

ingress:
  host: ""
  annotations: {}
