image:
  repository: ghcr.io/japan7/dakara-client-web
  tag: master@sha256:160c93017dfddc0c84bf592ea1acd1dda6688aaae3026d107e5fe907916d0fce
  pullPolicy: ""

replicaCount: 1

affinity: {}

ingress:
  host: ""
  annotations: {}
