image:
  repository: ghcr.io/japan7/dakara-client-web
  tag: master@sha256:ec6aeaaf02067afcc7890793eb55de4f478d7bbf22f33b92e825c7c65d87cd82
  pullPolicy: ""

replicaCount: 1

affinity: {}

ingress:
  host: ""
  annotations: {}
