image:
  repository: ghcr.io/japan7/dakara-client-web
  tag: master@sha256:9df0073a1830e7920987747a47d4a686589632336776747010e515bc7a7ed760
  pullPolicy: ""

replicaCount: 1

affinity: {}

ingress:
  host: ""
  annotations: {}
