image:
  repository: ghcr.io/japan7/dakara-client-web
  tag: master@sha256:f82cc61eeb7606d4bbe1d6882b0ddcc4e67c1bad931b00b301e4a69eeba4c0d6
  pullPolicy: ""

replicaCount: 1

affinity: {}

ingress:
  host: ""
  annotations: {}
