image:
  repository: ghcr.io/japan7/dakara-client-web
  tag: master@sha256:964a4b5acf694f6f280a40bebd2c37df6af8fdbb64052bbb82a79c181a6b0211
  pullPolicy: ""

replicaCount: 1

affinity: {}

ingress:
  host: ""
  annotations: {}
