image:
  repository: outlinewiki/outline
  tag: 0.76.1
  pullPolicy: ""

replicaCount: 1

updateStrategy:
  type: RollingUpdate

affinity: {}

cnpg:
  secretName: ""

env: ""

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
  labels: {}

ingress:
  host: ""
  annotations: {}
