image:
  repository: outlinewiki/outline
  tag: 1.1.0
  pullPolicy: ""

replicaCount: 1

updateStrategy:
  type: RollingUpdate

affinity: {}

cnpg:
  secretName: ""

env: ""

ingress:
  host: ""
  annotations: {}
