apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-data
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: extras
    app.kubernetes.io/part-of: traefik
    {{- .Values.persistence.labels | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
