image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:01e0f94d45377025681a1cf0b041909eeb90fbf7c8e4140b971ff55bbc04b51c
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
