image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:2d88b370b685ce06d150efaa8485598b16571e135eb2e92d09845979f7b84dda
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
