image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:5e3b7fc15da837aeae9b3a1ba448f1522e1dcfb333e12097130faf3a945410cd
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
