image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:dafc0b51b397b4de66a6eecb6c837692bfd41a68ff101498727ebda8383f3a5c
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
