image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:6d07631f1ed061800a80af520e2bc69046fff73739960842fc1b9c3ade5987d1
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
