image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:e8a24fe8022f633fd0e75549a0ecbd2bc06a7731df09da0162451f9ed5e833f5
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
