image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:2edea21b127747253d59ef1cb27ceb9ed39e7431dfdcf767ce8e58b7c3b2e4ed
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
