image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:451d2518065761d2bfab05629851a9266e376da9f6d9f2f3bf5e98a739350762
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
