image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:c998e9f703c186947666da00949105dcc9a316a08d289fcc2d19fa43e67538f8
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
