image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:74fcf2d15703723207a250947cf433314fb1770113cd611281d56bf60e64190a
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
