image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:37aa4c186af685e66f34569faa455eff7310432bd4a5b2058f88438d7af655f6
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
