image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:1e71d585c7ffe2ce05bdea534b4e5182601065373fbddb2f1a5ed3249844144e
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
