image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:c7c2640f4948d22791c0477e14492b10a25477a5015722e244d9aac620ab5ba1
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
