image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:5874e0cad9198dfa5b800737e39ab7f1fa57fc8d8cfddff2f3b68c724abd905e
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
