image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:8f056597f535b456ccf0cb4a02274954b5100a08088f5bfd9464aa9cbff293ca
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
