image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:12eb8b26d9a53e600eb339f7977c4e55885e2a165ebec08cf209041f48e7fc87
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
