image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:343c30992b5e7ab207c65b8b28e7a7f3b7df98932696b744d6b4401eb3abdb41
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
