image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:5e84819110fecb67b47418c840a9a6b03c5d522187623d4e5112fea40abf6bc6
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
