image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:eaac617a335a81ae47134ee82bed7aaca7d3fc947ed93b07343afab3a1b76133
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
