image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:5d0b3aad7cde8e202c8afc9a372884179297a2b64b48caecdc5415441f94a33c
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
