image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:9c970f30bcba8ed05fe38cc955fb7bf213222aef0bd01ae24803d1639451a398
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
