image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:5c5802428eb83860f0d43bb7bc9370d8a1d22413b25fdd6efb0c7ec8373d0fcb
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
