image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:6162083b5428d8f7542df4a6a27452dec3997f89adfc9b547b02decd14d8098f
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
