image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:0f8270e294de2e2b4edcece70195c5138eb80d023c0c50f65816048334fbcb4b
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
