image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:9afd30ee8ab37bf298866a097b61bf9b9ae354d7d7cc84fb7060739f844e4d68
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
