image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:59a1b5efddc84d300901ed999b02455b29f11d7da29ce67d67876becbdb353aa
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
