image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:1ba74d2272bebf55d57a78baf4456a0807270cb22957ad279d4acc724af6b79d
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
