image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:a3c7a3ea1cb81e83588cf142eb4ff6679008f063ccd7be1217a016e70939670c
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
