image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:4aee67450b4f77f12fd8e4a0efe4f51f37a73bdc932bf83b67ec107ff2b87bec
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
