image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:52d5cbc89400064f3a4017cb62b497123f1732451c9498b8018e37f636bb67d2
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
