image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:ae6d3ee8ee7f401c02ff5eefd196da9d77e58e29e19f690a6767137ffd53cb03
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
