image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:b378fcdc4b599d5e89efb04d0150b9dd90e0bce4bf0aff92badb031e2b9e0c46
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
