image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:b48c7f5304a819fe9314ac09a9d2435ba717e7bfabf43bf46a18e17fe39a254e
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
