image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:b6da4b9da2748fd965e1029128d6e621aa24a9d08ddce50beb96270c293dbdd7
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
