image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:01f419eecb425d164748e306df76e0e5d3bef371495460451e84742f66fdfa50
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
