image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:a6be5496e7d868800194067043faeda7ae6b4bbf24e8b692d3161087762e5415
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
