image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:94846f276ffb3f8810441afb6389421b936a6b2e2bfbca3ee186f4669db9f55a
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
