image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:4f3749e2dddf09dc652703874eca96abfbc0d6be19e9e8343e776e9cc884301e
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
