image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:fe3d59a8d28882e73797dad0bb938dd5820bd18ec805302fb4ed8c34b9d9c94d
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
