image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:fca8a57db7d9231a3cf52466f9b5e6d994fc41502cb9361035f78a7502aab2d3
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
