image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:849492c9d59952833fbd28bf275d69941427d2cca41121843699c7732fd8968d
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
