image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:6cd43e4e89ed5f62ba29baab7665a233227643ead5264943f5090dea1d3bce30
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
