image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:f910ed0a2e20be85caac4017433db89757dae9cc62ac63afacf4a7f826461b97
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
