image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:cabf340915432ac3c63db15270ea7795ca1041db3645d35834b5f8e7520b9554
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
