image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:41d0aafa4432464ad2cf726f3cadfa3acf10011199a156735dee251fe68a3a7e
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
