image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:fefe5ef9bf9b9340c1eb04f238c79ea3acdbb7d77d134888ee2dc3cf5e053d19
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
