image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:69874054c5414b99629702fc8e816e76e850e2fd61a717be82f9f45061666aff
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
