image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:e224792c37f2594f1c2a3ea12d63c0b8c42936cc082aa97334f15c9552205c14
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
