image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:933afebcd91d6aac489bb3f30b826cfd6879d3cd036f01ce6d46896c469f9f32
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
