image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:6d343b179326b33f35cd1d1f0d007dd8ef8b4fc0181b20fb395b9ab84b245f1d
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
