image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:85286ca772eaf127b570c1decbce15c615228b7517b31115fabec35db4120401
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
