image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:a568a24768950ad6c2a78c58c893491116924e0d0cb894dfdebaf4124526b960
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
