image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:fd3246555663788b80f852e1ba917fc44d2285b3a4f273ffeda2b018fe63cdda
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
