image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:ec2da962e3e31aa84dfa0bec73c5d069e88bef0f29d137f938a04fb11ab732bb
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
