image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:19c2611f2d674c4894618d02c6f7d70ed9a879a080358b6ee6a73a42aaec7d92
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
