image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:a0d0d2c204ee62c5c45a38d1154c961130c8d5fc28e062398cbc93bde2c26008
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
