image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:903d359e78e2f8d7623ac189ba19d5c89ca403cc45ff417a71a005ff6724894c
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
