image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:60a35eb9fe000183ef04b059c457af639fd18c75384092e79d06d5a71a8cfd8d
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
