environments:
  default:
    values:
      - garage:
          addresses:
            - 10.100.0.2
            - 10.100.0.4
            - 10.100.0.10
            - 10.100.0.11
    secrets:
      - ../globals.sops.yaml
      - default.sops.yaml
