image:
  repository: ghcr.io/japan7/producer
  tag: main@sha256:75172c5b126d062cb67af29576e1bf3559f18304ae8d06d4c3e14a297757a062
  pullPolicy: ""

replicaCount: 1

affinity: {}

upload:
  baseUrl: ""
  adminToken: ""

s3:
  endpoints: []
  secure: false
  keyId: ""
  secret: ""

ingress:
  host: ""
  annotations: {}
