image:
  repository: ghcr.io/japan7/producer
  tag: main@sha256:eafdb73185155aae1b48f5ac9dafc4e075541d3038c593305d6eb22d4648d68b
  pullPolicy: ""

replicaCount: 1

affinity: {}

upload:
  baseUrl: ""
  adminToken: ""

s3:
  endpoints: []
  secure: false
  keyId: ""
  secret: ""

ingress:
  host: ""
  annotations: {}
