image:
  repository: ghcr.io/japan7/producer
  tag: main@sha256:22492b1feaf5cf5c260feb5876fd56db73ff76bf3b228160bd620ef693c35536
  pullPolicy: ""

replicaCount: 1

affinity: {}

upload:
  baseUrl: ""
  adminToken: ""

s3:
  endpoints: []
  secure: false
  keyId: ""
  secret: ""

ingress:
  host: ""
  annotations: {}
