image:
  repository: ghcr.io/japan7/producer
  tag: main@sha256:3b79702d38abbcbdf23a3f6797a8b8b9aa2aee8b8b95197ee47d08700ff6afb4
  pullPolicy: ""

replicaCount: 1

affinity: {}

upload:
  baseUrl: ""
  adminToken: ""

s3:
  endpoints: []
  secure: false
  keyId: ""
  secret: ""

ingress:
  host: ""
  annotations: {}
