image:
  repository: ghcr.io/japan7/producer
  tag: main@sha256:7b84855f585006ded8411bb403482b136ede1141ca62ecd0c1f8e9e9d5cc0158
  pullPolicy: ""

replicaCount: 1

affinity: {}

upload:
  baseUrl: ""
  adminToken: ""

s3:
  endpoints: []
  secure: false
  keyId: ""
  secret: ""

ingress:
  host: ""
  annotations: {}
