image:
  repository: ghcr.io/japan7/producer
  tag: main@sha256:cba908fb38003d06d8140b36ca7a1ac3ed092bb7e1bf11d3dda8d94355cc4854
  pullPolicy: ""

replicaCount: 1

affinity: {}

upload:
  baseUrl: ""
  adminToken: ""

s3:
  endpoints: []
  secure: false
  keyId: ""
  secret: ""

ingress:
  host: ""
  annotations: {}
