image:
  repository: ghcr.io/japan7/producer
  tag: main@sha256:61861cd7f690eb926fb9f10e4217d19e45c1a77b39f4458ba12f64db0e708490
  pullPolicy: ""

replicaCount: 1

affinity: {}

upload:
  baseUrl: ""
  adminToken: ""

s3:
  endpoints: []
  secure: false
  keyId: ""
  secret: ""

ingress:
  host: ""
  annotations: {}
