image:
  repository: ghcr.io/japan7/producer
  tag: main@sha256:2a78082641d857b9d9c277b0ff5bc8ff91dabd5ef80318d371f5dfe208a27c8f
  pullPolicy: ""

replicaCount: 1

affinity: {}

upload:
  baseUrl: ""
  adminToken: ""

s3:
  endpoints: []
  secure: false
  keyId: ""
  secret: ""

ingress:
  host: ""
  annotations: {}
