image:
  repository: ghcr.io/japan7/producer
  tag: main@sha256:b2ad3a9cfba3c53072a43de2caa2872fd875e21e9dd409b2225cbd0d784b32d8
  pullPolicy: ""

replicaCount: 1

affinity: {}

upload:
  baseUrl: ""
  adminToken: ""

s3:
  endpoints: []
  secure: false
  keyId: ""
  secret: ""

ingress:
  host: ""
  annotations: {}
