image:
  repository: ghcr.io/japan7/producer
  tag: main@sha256:437836c739a464a64b7c5b76f2c4def40c4c0845781a824a3ae5184bdd1eb346
  pullPolicy: ""

replicaCount: 1

affinity: {}

upload:
  baseUrl: ""
  adminToken: ""

s3:
  endpoints: []
  secure: false
  keyId: ""
  secret: ""

ingress:
  host: ""
  annotations: {}
