image:
  repository: ghcr.io/japan7/producer
  tag: main@sha256:a0703591d0a6ff3deed3b6831dae4bf6e60574c0a3fc1011da5856e04a943348
  pullPolicy: ""

replicaCount: 1

affinity: {}

upload:
  baseUrl: ""
  adminToken: ""

s3:
  endpoints: []
  secure: false
  keyId: ""
  secret: ""

ingress:
  host: ""
  annotations: {}
