apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-http-stub"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: http-stub
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: http-stub
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  ports:
    - port: 80
